apiVersion: v1
kind: Service
metadata:
  name: rest-server-service
  namespace: pwa-kkuang
spec:
  selector:
    app: rest-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
